# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewPersonObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('father_name', models.CharField(blank=True, max_length=80, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_found', models.BooleanField(default=False)),
            ],
        ),
    ]
